extends TileMap

#Instance of fastnoiselite library for
#perling noise and other types of noise generation
var fnl := FastNoiseLite.new();

#This variable holds the noise value from a given
#position in the noise image generated by "fnl:
#FastNoiseLite
#Unless set, this variable is null by default
var noiseVal = null;

#This variable is the size of the map that is visible
#The map will be square, so this value is the length
#of both sides.
var mapSize : int = 120;


#These are the horizontal and verticle
#vectors for the maps movement.
#Defines speed and direction of movement depending on
#if the variable is negative or positive.
#-----
#Horizontal:
#Negative: South
#Positive: North
#-----
#Vertical:
#Negative: West
#Positive: East
var horizontal_vector = 0.0;
var vertical_vector = 0.0;

#Time that has passed since the map last scrolled 1 vector
#(horizontal and verticle)
var time : float = 0.0;

#The speed the background can scroll.
var backgroundSpeed : int = 1;

#World position of the world in the background.
#This position is just a Vector2, which we update as the world moves,
#similar to the frag point in game. We then use a for loop
#later in "generateMap()" to move around/ahead the world position
#to figure out what the next blocks will be.
var backgroundWorldPosition : Vector2 = Vector2(0.0, 0.0);

#This variable points to the scenes root tree.
#So you can use ".get_node()" on it to
#get a node from anywhere in the scene
var root;


#Entry point, this function runs when
#the application first executes
func _ready() -> void:
	
	#Point the root variable at the root of the scene tree.
	#This will allow us to get a node from anywhere in the
	#scene later using "get_node()"
	root = get_tree().get_root();
	
	#Choose seed, and other important
	#data for the map, set it up.
	intializeMap();
	
	#Intialize the direction and speed of movement for each axis on the
	#world map.
	initalizeRandomMapSpeedAndDirection();
	




#Runs each frame/application cycle
func _process(delta: float) -> void:
	
	#Render the map at the current camera position
	#Keep rendering the map if needed.
	generateMap();
	
	#Increase the corrdinates each frame, so that the
	#maps scrolls south or north, east or west.
	scrollMap(delta);
	
	pass;


#Scrolls the map based on the vertical and horizontal speed.
func scrollMap(delta) -> void:
	
	#Compute the ammount of time that has passed since
	#the last frame. Then add it to the time
	#since the background scrolled 1 vector (horizontal and verticle).
	#We will use this to figure out when to move the map again.
	time = time + (delta * 1000);
	
	#If its been longer than 40 milliseconds since
	#the map moved, then move it 1 vector (horizontal and verticle).
	if (time > 40):
		time = 0; #Reset the time to zero, then move 1 vector.
	else:
		return; #Its been less than 40 milliseconds, skip this function and don't scroll the map.
	
	#Add the movement vectors and direction to each axis
	#of the current world corrdinates "backgroundWorldPosition".
	backgroundWorldPosition.x = backgroundWorldPosition.x + horizontal_vector;
	backgroundWorldPosition.y = backgroundWorldPosition.y + vertical_vector;
	
	pass;



#Randomly choose which direction and at what speed the
#background slowly scrolls
func initalizeRandomMapSpeedAndDirection() -> void:
	
	#Set the horizontal and verticle speed vectors
	#of the background scroll to the background speed.
	horizontal_vector = backgroundSpeed;
	vertical_vector = backgroundSpeed;
	
	#ID: ydtwmmd27
	#Now, we randomly choose direction the background scrolls
	#with random integers between -100 and 100.
	#If above 0 or at 0, then the vector is positive.
	#If below, then the vector is negative.
	#First, set the horizontal vectors direction
	if (randi_range(-100, 100) >= 0):
		pass #"horizontal_vector" will remain positive.
	else:
		#Horizaontal Vector will become negative
		horizontal_vector = horizontal_vector * -1;
	
	#Now we set the verticle vector according to
	#rules defined in ID: ydtwmmd27
	if (randi_range(-100, 100) >= 0):
		pass #"vertical_vector" will remain positive.
	else:
		#Horizaontal Vector will become negative
		vertical_vector = vertical_vector * -1;
	
	pass;


#Intializes parameters reguarding the map
#Sets the fnl (FlatNoiseLite) seed
#and other variables regaurding the generation
func intializeMap() -> void:
	
	#Choose a random seed for FlatNoiseLite
	#choose in range of the random
	#number generator
	fnl.seed = randi_range(0, 1000000);
	
	fnl.noise_type = FastNoiseLite.TYPE_SIMPLEX;
	
	
	pass;



#Generates a map using noise.
#and displays it on the screen using the
#TileMap "TileMap".
func generateMap() -> void:
	
	#Runs each "x" and "y" from 
	#the world through a noise image, based on the intensity
	#at each point on the map, we determine what type of
	#map terrain we want to spawn.
	for x in mapSize: #Loop along each X value/corrdinate in the world
		for y in mapSize: #Loop along each Y value/corrdinate in the world
			
			#Get the noise value from a point on the Noise Image
			#that was generated from "fnl" (FlatNoiseLite)
			#Get the position of the top left of "TileMap" (world corrdinates)
			#and find the corresponding noise to the same position
			#in "fnl". Then we add x or y (from the for loop) as we move
			#along the X and Y, filling each cell in the tile map with a
			#color corresponding to noise at that position.
			noiseVal = fnl.get_noise_2d(backgroundWorldPosition.x + x, backgroundWorldPosition.y + y);
			
			#Set each sell to a specific terrain in the world, based on the level
			#of noise from the given corrdinate in the noise map.
			if (noiseVal < -0.5): #Hot desert
				set_cell(0, Vector2i(x, y), 0, Vector2(2, 4));
			elif (noiseVal > -0.5 && noiseVal < -0.3): #Normal desert
				set_cell(0, Vector2i(x, y), 0, Vector2(0, 0));
			elif (noiseVal > -0.3 && 0.33 > noiseVal): #Water
				set_cell(0, Vector2i(x, y), 0, Vector2(2, 0));
			elif (noiseVal > 0.33 && noiseVal < 0.35): #Beach
				set_cell(0, Vector2i(x, y), 0, Vector2(0, 0));
			elif (noiseVal > 0.35 && noiseVal < 0.4): #Grass
				set_cell(0, Vector2i(x, y), 0, Vector2(0, 2));
			elif (noiseVal > 0.4 && noiseVal < 0.5): #Jungle
				set_cell(0, Vector2i(x, y), 0, Vector2(2, 2));
			elif (noiseVal > 0.5): #Snow
				set_cell(0, Vector2i(x, y), 0, Vector2(0, 4));
	
	pass;
